/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSettingRouteImport } from './routes/_protected/setting'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ApiShopIndexRouteImport } from './routes/api/shop/index'
import { Route as ApiSaleIndexRouteImport } from './routes/api/sale/index'
import { Route as ApiMenuFoodItemIndexRouteImport } from './routes/api/menuFoodItem/index'
import { Route as ApiMenuIndexRouteImport } from './routes/api/menu/index'
import { Route as ApiMachineIndexRouteImport } from './routes/api/machine/index'
import { Route as ApiLocationIndexRouteImport } from './routes/api/location/index'
import { Route as ApiInventoryIndexRouteImport } from './routes/api/inventory/index'
import { Route as ApiFoodItemIndexRouteImport } from './routes/api/foodItem/index'
import { Route as ApiDisposeIndexRouteImport } from './routes/api/dispose/index'
import { Route as ApiDeliveryIndexRouteImport } from './routes/api/delivery/index'
import { Route as ApiShopIdRouteImport } from './routes/api/shop/$id'
import { Route as ApiSaleIdRouteImport } from './routes/api/sale/$id'
import { Route as ApiR2UploadRouteImport } from './routes/api/r2/upload'
import { Route as ApiR2DownloadRouteImport } from './routes/api/r2/download'
import { Route as ApiMenuIdRouteImport } from './routes/api/menu/$id'
import { Route as ApiMachineIdRouteImport } from './routes/api/machine/$id'
import { Route as ApiLocationIdRouteImport } from './routes/api/location/$id'
import { Route as ApiInventoryIdRouteImport } from './routes/api/inventory/$id'
import { Route as ApiFoodItemIdRouteImport } from './routes/api/foodItem/$id'
import { Route as ApiDisposeIdRouteImport } from './routes/api/dispose/$id'
import { Route as ApiDeliveryIdRouteImport } from './routes/api/delivery/$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedDashboardWeeklySalesIndexRouteImport } from './routes/_protected/dashboard/weekly-sales/index'
import { Route as ProtectedDashboardUsersIndexRouteImport } from './routes/_protected/dashboard/users/index'
import { Route as ProtectedDashboardShopsIndexRouteImport } from './routes/_protected/dashboard/shops/index'
import { Route as ProtectedDashboardSchedulesIndexRouteImport } from './routes/_protected/dashboard/schedules/index'
import { Route as ProtectedDashboardSalesIndexRouteImport } from './routes/_protected/dashboard/sales/index'
import { Route as ProtectedDashboardMenusIndexRouteImport } from './routes/_protected/dashboard/menus/index'
import { Route as ProtectedDashboardMachinesIndexRouteImport } from './routes/_protected/dashboard/machines/index'
import { Route as ProtectedDashboardLocationsIndexRouteImport } from './routes/_protected/dashboard/locations/index'
import { Route as ProtectedDashboardInventoriesIndexRouteImport } from './routes/_protected/dashboard/inventories/index'
import { Route as ProtectedDashboardFoodItemsIndexRouteImport } from './routes/_protected/dashboard/food-items/index'
import { Route as ProtectedDashboardFaqsIndexRouteImport } from './routes/_protected/dashboard/faqs/index'
import { Route as ProtectedDashboardDisposesIndexRouteImport } from './routes/_protected/dashboard/disposes/index'
import { Route as ProtectedDashboardDeliveriesIndexRouteImport } from './routes/_protected/dashboard/deliveries/index'
import { Route as ProtectedDashboardDailySalesIndexRouteImport } from './routes/_protected/dashboard/daily-sales/index'
import { Route as ProtectedDashboardBrandingIndexRouteImport } from './routes/_protected/dashboard/branding/index'
import { Route as ProtectedDashboardAdminOnlyIndexRouteImport } from './routes/_protected/dashboard/admin-only/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedSettingRoute = ProtectedSettingRouteImport.update({
  id: '/setting',
  path: '/setting',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiShopIndexRoute = ApiShopIndexRouteImport.update({
  id: '/api/shop/',
  path: '/api/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaleIndexRoute = ApiSaleIndexRouteImport.update({
  id: '/api/sale/',
  path: '/api/sale/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuFoodItemIndexRoute = ApiMenuFoodItemIndexRouteImport.update({
  id: '/api/menuFoodItem/',
  path: '/api/menuFoodItem/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuIndexRoute = ApiMenuIndexRouteImport.update({
  id: '/api/menu/',
  path: '/api/menu/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMachineIndexRoute = ApiMachineIndexRouteImport.update({
  id: '/api/machine/',
  path: '/api/machine/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationIndexRoute = ApiLocationIndexRouteImport.update({
  id: '/api/location/',
  path: '/api/location/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryIndexRoute = ApiInventoryIndexRouteImport.update({
  id: '/api/inventory/',
  path: '/api/inventory/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoodItemIndexRoute = ApiFoodItemIndexRouteImport.update({
  id: '/api/foodItem/',
  path: '/api/foodItem/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisposeIndexRoute = ApiDisposeIndexRouteImport.update({
  id: '/api/dispose/',
  path: '/api/dispose/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliveryIndexRoute = ApiDeliveryIndexRouteImport.update({
  id: '/api/delivery/',
  path: '/api/delivery/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopIdRoute = ApiShopIdRouteImport.update({
  id: '/api/shop/$id',
  path: '/api/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSaleIdRoute = ApiSaleIdRouteImport.update({
  id: '/api/sale/$id',
  path: '/api/sale/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2UploadRoute = ApiR2UploadRouteImport.update({
  id: '/api/r2/upload',
  path: '/api/r2/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiR2DownloadRoute = ApiR2DownloadRouteImport.update({
  id: '/api/r2/download',
  path: '/api/r2/download',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMenuIdRoute = ApiMenuIdRouteImport.update({
  id: '/api/menu/$id',
  path: '/api/menu/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMachineIdRoute = ApiMachineIdRouteImport.update({
  id: '/api/machine/$id',
  path: '/api/machine/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLocationIdRoute = ApiLocationIdRouteImport.update({
  id: '/api/location/$id',
  path: '/api/location/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventoryIdRoute = ApiInventoryIdRouteImport.update({
  id: '/api/inventory/$id',
  path: '/api/inventory/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoodItemIdRoute = ApiFoodItemIdRouteImport.update({
  id: '/api/foodItem/$id',
  path: '/api/foodItem/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisposeIdRoute = ApiDisposeIdRouteImport.update({
  id: '/api/dispose/$id',
  path: '/api/dispose/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeliveryIdRoute = ApiDeliveryIdRouteImport.update({
  id: '/api/delivery/$id',
  path: '/api/delivery/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardWeeklySalesIndexRoute =
  ProtectedDashboardWeeklySalesIndexRouteImport.update({
    id: '/weekly-sales/',
    path: '/weekly-sales/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardUsersIndexRoute =
  ProtectedDashboardUsersIndexRouteImport.update({
    id: '/users/',
    path: '/users/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardShopsIndexRoute =
  ProtectedDashboardShopsIndexRouteImport.update({
    id: '/shops/',
    path: '/shops/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSchedulesIndexRoute =
  ProtectedDashboardSchedulesIndexRouteImport.update({
    id: '/schedules/',
    path: '/schedules/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSalesIndexRoute =
  ProtectedDashboardSalesIndexRouteImport.update({
    id: '/sales/',
    path: '/sales/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardMenusIndexRoute =
  ProtectedDashboardMenusIndexRouteImport.update({
    id: '/menus/',
    path: '/menus/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardMachinesIndexRoute =
  ProtectedDashboardMachinesIndexRouteImport.update({
    id: '/machines/',
    path: '/machines/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardLocationsIndexRoute =
  ProtectedDashboardLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardInventoriesIndexRoute =
  ProtectedDashboardInventoriesIndexRouteImport.update({
    id: '/inventories/',
    path: '/inventories/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardFoodItemsIndexRoute =
  ProtectedDashboardFoodItemsIndexRouteImport.update({
    id: '/food-items/',
    path: '/food-items/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardFaqsIndexRoute =
  ProtectedDashboardFaqsIndexRouteImport.update({
    id: '/faqs/',
    path: '/faqs/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardDisposesIndexRoute =
  ProtectedDashboardDisposesIndexRouteImport.update({
    id: '/disposes/',
    path: '/disposes/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardDeliveriesIndexRoute =
  ProtectedDashboardDeliveriesIndexRouteImport.update({
    id: '/deliveries/',
    path: '/deliveries/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardDailySalesIndexRoute =
  ProtectedDashboardDailySalesIndexRouteImport.update({
    id: '/daily-sales/',
    path: '/daily-sales/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardBrandingIndexRoute =
  ProtectedDashboardBrandingIndexRouteImport.update({
    id: '/branding/',
    path: '/branding/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardAdminOnlyIndexRoute =
  ProtectedDashboardAdminOnlyIndexRouteImport.update({
    id: '/admin-only/',
    path: '/admin-only/',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/setting': typeof ProtectedSettingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/delivery/$id': typeof ApiDeliveryIdRoute
  '/api/dispose/$id': typeof ApiDisposeIdRoute
  '/api/foodItem/$id': typeof ApiFoodItemIdRoute
  '/api/inventory/$id': typeof ApiInventoryIdRoute
  '/api/location/$id': typeof ApiLocationIdRoute
  '/api/machine/$id': typeof ApiMachineIdRoute
  '/api/menu/$id': typeof ApiMenuIdRoute
  '/api/r2/download': typeof ApiR2DownloadRoute
  '/api/r2/upload': typeof ApiR2UploadRoute
  '/api/sale/$id': typeof ApiSaleIdRoute
  '/api/shop/$id': typeof ApiShopIdRoute
  '/api/delivery/': typeof ApiDeliveryIndexRoute
  '/api/dispose/': typeof ApiDisposeIndexRoute
  '/api/foodItem/': typeof ApiFoodItemIndexRoute
  '/api/inventory/': typeof ApiInventoryIndexRoute
  '/api/location/': typeof ApiLocationIndexRoute
  '/api/machine/': typeof ApiMachineIndexRoute
  '/api/menu/': typeof ApiMenuIndexRoute
  '/api/menuFoodItem/': typeof ApiMenuFoodItemIndexRoute
  '/api/sale/': typeof ApiSaleIndexRoute
  '/api/shop/': typeof ApiShopIndexRoute
  '/dashboard/admin-only/': typeof ProtectedDashboardAdminOnlyIndexRoute
  '/dashboard/branding/': typeof ProtectedDashboardBrandingIndexRoute
  '/dashboard/daily-sales/': typeof ProtectedDashboardDailySalesIndexRoute
  '/dashboard/deliveries/': typeof ProtectedDashboardDeliveriesIndexRoute
  '/dashboard/disposes/': typeof ProtectedDashboardDisposesIndexRoute
  '/dashboard/faqs/': typeof ProtectedDashboardFaqsIndexRoute
  '/dashboard/food-items/': typeof ProtectedDashboardFoodItemsIndexRoute
  '/dashboard/inventories/': typeof ProtectedDashboardInventoriesIndexRoute
  '/dashboard/locations/': typeof ProtectedDashboardLocationsIndexRoute
  '/dashboard/machines/': typeof ProtectedDashboardMachinesIndexRoute
  '/dashboard/menus/': typeof ProtectedDashboardMenusIndexRoute
  '/dashboard/sales/': typeof ProtectedDashboardSalesIndexRoute
  '/dashboard/schedules/': typeof ProtectedDashboardSchedulesIndexRoute
  '/dashboard/shops/': typeof ProtectedDashboardShopsIndexRoute
  '/dashboard/users/': typeof ProtectedDashboardUsersIndexRoute
  '/dashboard/weekly-sales/': typeof ProtectedDashboardWeeklySalesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/setting': typeof ProtectedSettingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/delivery/$id': typeof ApiDeliveryIdRoute
  '/api/dispose/$id': typeof ApiDisposeIdRoute
  '/api/foodItem/$id': typeof ApiFoodItemIdRoute
  '/api/inventory/$id': typeof ApiInventoryIdRoute
  '/api/location/$id': typeof ApiLocationIdRoute
  '/api/machine/$id': typeof ApiMachineIdRoute
  '/api/menu/$id': typeof ApiMenuIdRoute
  '/api/r2/download': typeof ApiR2DownloadRoute
  '/api/r2/upload': typeof ApiR2UploadRoute
  '/api/sale/$id': typeof ApiSaleIdRoute
  '/api/shop/$id': typeof ApiShopIdRoute
  '/api/delivery': typeof ApiDeliveryIndexRoute
  '/api/dispose': typeof ApiDisposeIndexRoute
  '/api/foodItem': typeof ApiFoodItemIndexRoute
  '/api/inventory': typeof ApiInventoryIndexRoute
  '/api/location': typeof ApiLocationIndexRoute
  '/api/machine': typeof ApiMachineIndexRoute
  '/api/menu': typeof ApiMenuIndexRoute
  '/api/menuFoodItem': typeof ApiMenuFoodItemIndexRoute
  '/api/sale': typeof ApiSaleIndexRoute
  '/api/shop': typeof ApiShopIndexRoute
  '/dashboard/admin-only': typeof ProtectedDashboardAdminOnlyIndexRoute
  '/dashboard/branding': typeof ProtectedDashboardBrandingIndexRoute
  '/dashboard/daily-sales': typeof ProtectedDashboardDailySalesIndexRoute
  '/dashboard/deliveries': typeof ProtectedDashboardDeliveriesIndexRoute
  '/dashboard/disposes': typeof ProtectedDashboardDisposesIndexRoute
  '/dashboard/faqs': typeof ProtectedDashboardFaqsIndexRoute
  '/dashboard/food-items': typeof ProtectedDashboardFoodItemsIndexRoute
  '/dashboard/inventories': typeof ProtectedDashboardInventoriesIndexRoute
  '/dashboard/locations': typeof ProtectedDashboardLocationsIndexRoute
  '/dashboard/machines': typeof ProtectedDashboardMachinesIndexRoute
  '/dashboard/menus': typeof ProtectedDashboardMenusIndexRoute
  '/dashboard/sales': typeof ProtectedDashboardSalesIndexRoute
  '/dashboard/schedules': typeof ProtectedDashboardSchedulesIndexRoute
  '/dashboard/shops': typeof ProtectedDashboardShopsIndexRoute
  '/dashboard/users': typeof ProtectedDashboardUsersIndexRoute
  '/dashboard/weekly-sales': typeof ProtectedDashboardWeeklySalesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/setting': typeof ProtectedSettingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/delivery/$id': typeof ApiDeliveryIdRoute
  '/api/dispose/$id': typeof ApiDisposeIdRoute
  '/api/foodItem/$id': typeof ApiFoodItemIdRoute
  '/api/inventory/$id': typeof ApiInventoryIdRoute
  '/api/location/$id': typeof ApiLocationIdRoute
  '/api/machine/$id': typeof ApiMachineIdRoute
  '/api/menu/$id': typeof ApiMenuIdRoute
  '/api/r2/download': typeof ApiR2DownloadRoute
  '/api/r2/upload': typeof ApiR2UploadRoute
  '/api/sale/$id': typeof ApiSaleIdRoute
  '/api/shop/$id': typeof ApiShopIdRoute
  '/api/delivery/': typeof ApiDeliveryIndexRoute
  '/api/dispose/': typeof ApiDisposeIndexRoute
  '/api/foodItem/': typeof ApiFoodItemIndexRoute
  '/api/inventory/': typeof ApiInventoryIndexRoute
  '/api/location/': typeof ApiLocationIndexRoute
  '/api/machine/': typeof ApiMachineIndexRoute
  '/api/menu/': typeof ApiMenuIndexRoute
  '/api/menuFoodItem/': typeof ApiMenuFoodItemIndexRoute
  '/api/sale/': typeof ApiSaleIndexRoute
  '/api/shop/': typeof ApiShopIndexRoute
  '/_protected/dashboard/admin-only/': typeof ProtectedDashboardAdminOnlyIndexRoute
  '/_protected/dashboard/branding/': typeof ProtectedDashboardBrandingIndexRoute
  '/_protected/dashboard/daily-sales/': typeof ProtectedDashboardDailySalesIndexRoute
  '/_protected/dashboard/deliveries/': typeof ProtectedDashboardDeliveriesIndexRoute
  '/_protected/dashboard/disposes/': typeof ProtectedDashboardDisposesIndexRoute
  '/_protected/dashboard/faqs/': typeof ProtectedDashboardFaqsIndexRoute
  '/_protected/dashboard/food-items/': typeof ProtectedDashboardFoodItemsIndexRoute
  '/_protected/dashboard/inventories/': typeof ProtectedDashboardInventoriesIndexRoute
  '/_protected/dashboard/locations/': typeof ProtectedDashboardLocationsIndexRoute
  '/_protected/dashboard/machines/': typeof ProtectedDashboardMachinesIndexRoute
  '/_protected/dashboard/menus/': typeof ProtectedDashboardMenusIndexRoute
  '/_protected/dashboard/sales/': typeof ProtectedDashboardSalesIndexRoute
  '/_protected/dashboard/schedules/': typeof ProtectedDashboardSchedulesIndexRoute
  '/_protected/dashboard/shops/': typeof ProtectedDashboardShopsIndexRoute
  '/_protected/dashboard/users/': typeof ProtectedDashboardUsersIndexRoute
  '/_protected/dashboard/weekly-sales/': typeof ProtectedDashboardWeeklySalesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/setting'
    | '/api/auth/$'
    | '/api/delivery/$id'
    | '/api/dispose/$id'
    | '/api/foodItem/$id'
    | '/api/inventory/$id'
    | '/api/location/$id'
    | '/api/machine/$id'
    | '/api/menu/$id'
    | '/api/r2/download'
    | '/api/r2/upload'
    | '/api/sale/$id'
    | '/api/shop/$id'
    | '/api/delivery/'
    | '/api/dispose/'
    | '/api/foodItem/'
    | '/api/inventory/'
    | '/api/location/'
    | '/api/machine/'
    | '/api/menu/'
    | '/api/menuFoodItem/'
    | '/api/sale/'
    | '/api/shop/'
    | '/dashboard/admin-only/'
    | '/dashboard/branding/'
    | '/dashboard/daily-sales/'
    | '/dashboard/deliveries/'
    | '/dashboard/disposes/'
    | '/dashboard/faqs/'
    | '/dashboard/food-items/'
    | '/dashboard/inventories/'
    | '/dashboard/locations/'
    | '/dashboard/machines/'
    | '/dashboard/menus/'
    | '/dashboard/sales/'
    | '/dashboard/schedules/'
    | '/dashboard/shops/'
    | '/dashboard/users/'
    | '/dashboard/weekly-sales/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/setting'
    | '/api/auth/$'
    | '/api/delivery/$id'
    | '/api/dispose/$id'
    | '/api/foodItem/$id'
    | '/api/inventory/$id'
    | '/api/location/$id'
    | '/api/machine/$id'
    | '/api/menu/$id'
    | '/api/r2/download'
    | '/api/r2/upload'
    | '/api/sale/$id'
    | '/api/shop/$id'
    | '/api/delivery'
    | '/api/dispose'
    | '/api/foodItem'
    | '/api/inventory'
    | '/api/location'
    | '/api/machine'
    | '/api/menu'
    | '/api/menuFoodItem'
    | '/api/sale'
    | '/api/shop'
    | '/dashboard/admin-only'
    | '/dashboard/branding'
    | '/dashboard/daily-sales'
    | '/dashboard/deliveries'
    | '/dashboard/disposes'
    | '/dashboard/faqs'
    | '/dashboard/food-items'
    | '/dashboard/inventories'
    | '/dashboard/locations'
    | '/dashboard/machines'
    | '/dashboard/menus'
    | '/dashboard/sales'
    | '/dashboard/schedules'
    | '/dashboard/shops'
    | '/dashboard/users'
    | '/dashboard/weekly-sales'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_protected/dashboard'
    | '/_protected/setting'
    | '/api/auth/$'
    | '/api/delivery/$id'
    | '/api/dispose/$id'
    | '/api/foodItem/$id'
    | '/api/inventory/$id'
    | '/api/location/$id'
    | '/api/machine/$id'
    | '/api/menu/$id'
    | '/api/r2/download'
    | '/api/r2/upload'
    | '/api/sale/$id'
    | '/api/shop/$id'
    | '/api/delivery/'
    | '/api/dispose/'
    | '/api/foodItem/'
    | '/api/inventory/'
    | '/api/location/'
    | '/api/machine/'
    | '/api/menu/'
    | '/api/menuFoodItem/'
    | '/api/sale/'
    | '/api/shop/'
    | '/_protected/dashboard/admin-only/'
    | '/_protected/dashboard/branding/'
    | '/_protected/dashboard/daily-sales/'
    | '/_protected/dashboard/deliveries/'
    | '/_protected/dashboard/disposes/'
    | '/_protected/dashboard/faqs/'
    | '/_protected/dashboard/food-items/'
    | '/_protected/dashboard/inventories/'
    | '/_protected/dashboard/locations/'
    | '/_protected/dashboard/machines/'
    | '/_protected/dashboard/menus/'
    | '/_protected/dashboard/sales/'
    | '/_protected/dashboard/schedules/'
    | '/_protected/dashboard/shops/'
    | '/_protected/dashboard/users/'
    | '/_protected/dashboard/weekly-sales/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDeliveryIdRoute: typeof ApiDeliveryIdRoute
  ApiDisposeIdRoute: typeof ApiDisposeIdRoute
  ApiFoodItemIdRoute: typeof ApiFoodItemIdRoute
  ApiInventoryIdRoute: typeof ApiInventoryIdRoute
  ApiLocationIdRoute: typeof ApiLocationIdRoute
  ApiMachineIdRoute: typeof ApiMachineIdRoute
  ApiMenuIdRoute: typeof ApiMenuIdRoute
  ApiR2DownloadRoute: typeof ApiR2DownloadRoute
  ApiR2UploadRoute: typeof ApiR2UploadRoute
  ApiSaleIdRoute: typeof ApiSaleIdRoute
  ApiShopIdRoute: typeof ApiShopIdRoute
  ApiDeliveryIndexRoute: typeof ApiDeliveryIndexRoute
  ApiDisposeIndexRoute: typeof ApiDisposeIndexRoute
  ApiFoodItemIndexRoute: typeof ApiFoodItemIndexRoute
  ApiInventoryIndexRoute: typeof ApiInventoryIndexRoute
  ApiLocationIndexRoute: typeof ApiLocationIndexRoute
  ApiMachineIndexRoute: typeof ApiMachineIndexRoute
  ApiMenuIndexRoute: typeof ApiMenuIndexRoute
  ApiMenuFoodItemIndexRoute: typeof ApiMenuFoodItemIndexRoute
  ApiSaleIndexRoute: typeof ApiSaleIndexRoute
  ApiShopIndexRoute: typeof ApiShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/setting': {
      id: '/_protected/setting'
      path: '/setting'
      fullPath: '/setting'
      preLoaderRoute: typeof ProtectedSettingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/shop/': {
      id: '/api/shop/'
      path: '/api/shop'
      fullPath: '/api/shop/'
      preLoaderRoute: typeof ApiShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sale/': {
      id: '/api/sale/'
      path: '/api/sale'
      fullPath: '/api/sale/'
      preLoaderRoute: typeof ApiSaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menuFoodItem/': {
      id: '/api/menuFoodItem/'
      path: '/api/menuFoodItem'
      fullPath: '/api/menuFoodItem/'
      preLoaderRoute: typeof ApiMenuFoodItemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu/': {
      id: '/api/menu/'
      path: '/api/menu'
      fullPath: '/api/menu/'
      preLoaderRoute: typeof ApiMenuIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/machine/': {
      id: '/api/machine/'
      path: '/api/machine'
      fullPath: '/api/machine/'
      preLoaderRoute: typeof ApiMachineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/location/': {
      id: '/api/location/'
      path: '/api/location'
      fullPath: '/api/location/'
      preLoaderRoute: typeof ApiLocationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/': {
      id: '/api/inventory/'
      path: '/api/inventory'
      fullPath: '/api/inventory/'
      preLoaderRoute: typeof ApiInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/foodItem/': {
      id: '/api/foodItem/'
      path: '/api/foodItem'
      fullPath: '/api/foodItem/'
      preLoaderRoute: typeof ApiFoodItemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dispose/': {
      id: '/api/dispose/'
      path: '/api/dispose'
      fullPath: '/api/dispose/'
      preLoaderRoute: typeof ApiDisposeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delivery/': {
      id: '/api/delivery/'
      path: '/api/delivery'
      fullPath: '/api/delivery/'
      preLoaderRoute: typeof ApiDeliveryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shop/$id': {
      id: '/api/shop/$id'
      path: '/api/shop/$id'
      fullPath: '/api/shop/$id'
      preLoaderRoute: typeof ApiShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sale/$id': {
      id: '/api/sale/$id'
      path: '/api/sale/$id'
      fullPath: '/api/sale/$id'
      preLoaderRoute: typeof ApiSaleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2/upload': {
      id: '/api/r2/upload'
      path: '/api/r2/upload'
      fullPath: '/api/r2/upload'
      preLoaderRoute: typeof ApiR2UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/r2/download': {
      id: '/api/r2/download'
      path: '/api/r2/download'
      fullPath: '/api/r2/download'
      preLoaderRoute: typeof ApiR2DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/menu/$id': {
      id: '/api/menu/$id'
      path: '/api/menu/$id'
      fullPath: '/api/menu/$id'
      preLoaderRoute: typeof ApiMenuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/machine/$id': {
      id: '/api/machine/$id'
      path: '/api/machine/$id'
      fullPath: '/api/machine/$id'
      preLoaderRoute: typeof ApiMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/location/$id': {
      id: '/api/location/$id'
      path: '/api/location/$id'
      fullPath: '/api/location/$id'
      preLoaderRoute: typeof ApiLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory/$id': {
      id: '/api/inventory/$id'
      path: '/api/inventory/$id'
      fullPath: '/api/inventory/$id'
      preLoaderRoute: typeof ApiInventoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/foodItem/$id': {
      id: '/api/foodItem/$id'
      path: '/api/foodItem/$id'
      fullPath: '/api/foodItem/$id'
      preLoaderRoute: typeof ApiFoodItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dispose/$id': {
      id: '/api/dispose/$id'
      path: '/api/dispose/$id'
      fullPath: '/api/dispose/$id'
      preLoaderRoute: typeof ApiDisposeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delivery/$id': {
      id: '/api/delivery/$id'
      path: '/api/delivery/$id'
      fullPath: '/api/delivery/$id'
      preLoaderRoute: typeof ApiDeliveryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/weekly-sales/': {
      id: '/_protected/dashboard/weekly-sales/'
      path: '/weekly-sales'
      fullPath: '/dashboard/weekly-sales/'
      preLoaderRoute: typeof ProtectedDashboardWeeklySalesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/users/': {
      id: '/_protected/dashboard/users/'
      path: '/users'
      fullPath: '/dashboard/users/'
      preLoaderRoute: typeof ProtectedDashboardUsersIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/shops/': {
      id: '/_protected/dashboard/shops/'
      path: '/shops'
      fullPath: '/dashboard/shops/'
      preLoaderRoute: typeof ProtectedDashboardShopsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/schedules/': {
      id: '/_protected/dashboard/schedules/'
      path: '/schedules'
      fullPath: '/dashboard/schedules/'
      preLoaderRoute: typeof ProtectedDashboardSchedulesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/sales/': {
      id: '/_protected/dashboard/sales/'
      path: '/sales'
      fullPath: '/dashboard/sales/'
      preLoaderRoute: typeof ProtectedDashboardSalesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/menus/': {
      id: '/_protected/dashboard/menus/'
      path: '/menus'
      fullPath: '/dashboard/menus/'
      preLoaderRoute: typeof ProtectedDashboardMenusIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/machines/': {
      id: '/_protected/dashboard/machines/'
      path: '/machines'
      fullPath: '/dashboard/machines/'
      preLoaderRoute: typeof ProtectedDashboardMachinesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/locations/': {
      id: '/_protected/dashboard/locations/'
      path: '/locations'
      fullPath: '/dashboard/locations/'
      preLoaderRoute: typeof ProtectedDashboardLocationsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/inventories/': {
      id: '/_protected/dashboard/inventories/'
      path: '/inventories'
      fullPath: '/dashboard/inventories/'
      preLoaderRoute: typeof ProtectedDashboardInventoriesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/food-items/': {
      id: '/_protected/dashboard/food-items/'
      path: '/food-items'
      fullPath: '/dashboard/food-items/'
      preLoaderRoute: typeof ProtectedDashboardFoodItemsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/faqs/': {
      id: '/_protected/dashboard/faqs/'
      path: '/faqs'
      fullPath: '/dashboard/faqs/'
      preLoaderRoute: typeof ProtectedDashboardFaqsIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/disposes/': {
      id: '/_protected/dashboard/disposes/'
      path: '/disposes'
      fullPath: '/dashboard/disposes/'
      preLoaderRoute: typeof ProtectedDashboardDisposesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/deliveries/': {
      id: '/_protected/dashboard/deliveries/'
      path: '/deliveries'
      fullPath: '/dashboard/deliveries/'
      preLoaderRoute: typeof ProtectedDashboardDeliveriesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/daily-sales/': {
      id: '/_protected/dashboard/daily-sales/'
      path: '/daily-sales'
      fullPath: '/dashboard/daily-sales/'
      preLoaderRoute: typeof ProtectedDashboardDailySalesIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/branding/': {
      id: '/_protected/dashboard/branding/'
      path: '/branding'
      fullPath: '/dashboard/branding/'
      preLoaderRoute: typeof ProtectedDashboardBrandingIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/admin-only/': {
      id: '/_protected/dashboard/admin-only/'
      path: '/admin-only'
      fullPath: '/dashboard/admin-only/'
      preLoaderRoute: typeof ProtectedDashboardAdminOnlyIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
  }
}

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardAdminOnlyIndexRoute: typeof ProtectedDashboardAdminOnlyIndexRoute
  ProtectedDashboardBrandingIndexRoute: typeof ProtectedDashboardBrandingIndexRoute
  ProtectedDashboardDailySalesIndexRoute: typeof ProtectedDashboardDailySalesIndexRoute
  ProtectedDashboardDeliveriesIndexRoute: typeof ProtectedDashboardDeliveriesIndexRoute
  ProtectedDashboardDisposesIndexRoute: typeof ProtectedDashboardDisposesIndexRoute
  ProtectedDashboardFaqsIndexRoute: typeof ProtectedDashboardFaqsIndexRoute
  ProtectedDashboardFoodItemsIndexRoute: typeof ProtectedDashboardFoodItemsIndexRoute
  ProtectedDashboardInventoriesIndexRoute: typeof ProtectedDashboardInventoriesIndexRoute
  ProtectedDashboardLocationsIndexRoute: typeof ProtectedDashboardLocationsIndexRoute
  ProtectedDashboardMachinesIndexRoute: typeof ProtectedDashboardMachinesIndexRoute
  ProtectedDashboardMenusIndexRoute: typeof ProtectedDashboardMenusIndexRoute
  ProtectedDashboardSalesIndexRoute: typeof ProtectedDashboardSalesIndexRoute
  ProtectedDashboardSchedulesIndexRoute: typeof ProtectedDashboardSchedulesIndexRoute
  ProtectedDashboardShopsIndexRoute: typeof ProtectedDashboardShopsIndexRoute
  ProtectedDashboardUsersIndexRoute: typeof ProtectedDashboardUsersIndexRoute
  ProtectedDashboardWeeklySalesIndexRoute: typeof ProtectedDashboardWeeklySalesIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardAdminOnlyIndexRoute: ProtectedDashboardAdminOnlyIndexRoute,
  ProtectedDashboardBrandingIndexRoute: ProtectedDashboardBrandingIndexRoute,
  ProtectedDashboardDailySalesIndexRoute:
    ProtectedDashboardDailySalesIndexRoute,
  ProtectedDashboardDeliveriesIndexRoute:
    ProtectedDashboardDeliveriesIndexRoute,
  ProtectedDashboardDisposesIndexRoute: ProtectedDashboardDisposesIndexRoute,
  ProtectedDashboardFaqsIndexRoute: ProtectedDashboardFaqsIndexRoute,
  ProtectedDashboardFoodItemsIndexRoute: ProtectedDashboardFoodItemsIndexRoute,
  ProtectedDashboardInventoriesIndexRoute:
    ProtectedDashboardInventoriesIndexRoute,
  ProtectedDashboardLocationsIndexRoute: ProtectedDashboardLocationsIndexRoute,
  ProtectedDashboardMachinesIndexRoute: ProtectedDashboardMachinesIndexRoute,
  ProtectedDashboardMenusIndexRoute: ProtectedDashboardMenusIndexRoute,
  ProtectedDashboardSalesIndexRoute: ProtectedDashboardSalesIndexRoute,
  ProtectedDashboardSchedulesIndexRoute: ProtectedDashboardSchedulesIndexRoute,
  ProtectedDashboardShopsIndexRoute: ProtectedDashboardShopsIndexRoute,
  ProtectedDashboardUsersIndexRoute: ProtectedDashboardUsersIndexRoute,
  ProtectedDashboardWeeklySalesIndexRoute:
    ProtectedDashboardWeeklySalesIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  ProtectedSettingRoute: typeof ProtectedSettingRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  ProtectedSettingRoute: ProtectedSettingRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDeliveryIdRoute: ApiDeliveryIdRoute,
  ApiDisposeIdRoute: ApiDisposeIdRoute,
  ApiFoodItemIdRoute: ApiFoodItemIdRoute,
  ApiInventoryIdRoute: ApiInventoryIdRoute,
  ApiLocationIdRoute: ApiLocationIdRoute,
  ApiMachineIdRoute: ApiMachineIdRoute,
  ApiMenuIdRoute: ApiMenuIdRoute,
  ApiR2DownloadRoute: ApiR2DownloadRoute,
  ApiR2UploadRoute: ApiR2UploadRoute,
  ApiSaleIdRoute: ApiSaleIdRoute,
  ApiShopIdRoute: ApiShopIdRoute,
  ApiDeliveryIndexRoute: ApiDeliveryIndexRoute,
  ApiDisposeIndexRoute: ApiDisposeIndexRoute,
  ApiFoodItemIndexRoute: ApiFoodItemIndexRoute,
  ApiInventoryIndexRoute: ApiInventoryIndexRoute,
  ApiLocationIndexRoute: ApiLocationIndexRoute,
  ApiMachineIndexRoute: ApiMachineIndexRoute,
  ApiMenuIndexRoute: ApiMenuIndexRoute,
  ApiMenuFoodItemIndexRoute: ApiMenuFoodItemIndexRoute,
  ApiSaleIndexRoute: ApiSaleIndexRoute,
  ApiShopIndexRoute: ApiShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
